config/routes.rb
Rails.application.routes.draw do

  get 'user/new'

  root 'website#home'

  namespace :api do
    resources :computations do
      collection do
        get :latest
      end
      member do
        get :form1040ez
        get :form540ez
      end
      resources :jobs do
        get :w4
        get :stateW4
      end
      resources :spouse do
        resources :jobs do
          get :w4
          get :stateW4
        end
      end
    end

    resources :draft_computations do
      collection do
        post :generate_actual_computation
      end
    end

    resources :invitations do
      collection do
        post :save_invite
      end
    end
  end

  namespace :admin do
    root 'dashboard#index'
    post 'refresh-graph', to: "dashboard#graph_info"

    get 'users' => 'user#index'
    get 'users/export' => 'user#export'
    put 'users/toggle' => 'user#toggle'

    put 'video/toggle' => 'video#toggle'
    put 'video/primary' => 'video#set_primary'

    resources :video do
    end
  end

  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :update => "update", :destroy => "destroy" }, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "forgot-password", to: "devise/passwords#new"
    get "change-password", to: "devise/passwords#edit"
    post "users/avatar", to: "registrations#avatar"
  end

  get 'home' => 'static_pages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'terms-and-conditions' => 'static_pages#terms_and_conditions'
  get 'tax' => 'tax#index'
  get 'resources' => 'video#index'

  get 'robots.txt' => 'static_pages#robots'

  #get 'funnel' => 'static_pages#funnel'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'website/application'

  def index
    if user_signed_in?
      redirect_to :tax
    end
  end

  def about
  end

  def contact
  end

  def privacy_policy
  end

  def terms_and_conditions
  end

  def robots
    robot_type = Rails.env == "production" ? "production" : "staging"
    robots = File.read(Rails.root + "config/robots/robots.#{robot_type}.txt")
    render :text => robots, :layout => false, :content_type => "text/plain"
  end

  def funnel
    render layout: false
  end
end

app/views/static_pages/_login_modal.html.haml
#loginmodal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}  
        %h2 Welcome to TaxBestimates
      .modal-body
        = form_for(resource, class: 'form col-md-12 center-block' , as: resource_name, url: session_path(resource_name)) do |f|
          .form-group
            = f.email_field :email, class: 'form-control input-lg', autofocus: true, placeholder: 'Email'
          .form-group
            = f.password_field :password, class: 'form-control input-lg', autocomplete: "off", placeholder: 'Password'
          .form-group.addtop
            = f.submit "Login to my Account", class: 'btn btn-primary btn-lg btn-block caps btnreg'
      .modal-footer
        %p.text-center
          = link_to "Forgot Password?", forgot_password_path
          |
          = link_to "Create an Account", register_path

app/views/static_pages/about.html.haml
= content_for :title, "About Us - TaxBestimates"
.innercont.gene
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2 Our Mission
        %p TaxBestimates Inc. is a Silicion Valley based company that is passionate about providing individual taxpayers with information they can use to simply manage their personal tax position. Our simple, yet sophisticated, tax platform will not only provide real-time tax information that can be used to manage your personal taxes, but it will provide tax recommendations that will optimize our users’ current period paycheck tax withholdings and year end task liability or refund.
    .row
      .col-md-8.col-md-offset-2
        %h2 How TaxBestimates Works
        %p TaxBestimates is a company that strives to make using our software as simple as possible as we understand that Year-End tax filings and managing payroll withholdings can be intimidating. With TaxBestimates, we have programmed our software to ask only the necessary questions based on your unique situation to improve your experience and provide our users with results, quicker.

app/views/static_pages/contact.html.haml
= content_for :title, "Contact - TaxBestimates"
.innercont.gene
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2 Contact Us
        %p We’re currently seeking partnerships with payroll, accounting, and insurance providers. If you feel like TaxBestimates may be a good partnership, we would love to hear from you.
        %p
          All partnership inquires should be sent to
          %a{href: 'mailto:info@taxbestimates.com?Subject=TaxBestimates%20Inquiry'}
            info@taxbestimates.com
          \.

app/views/static_pages/funnel.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8">
/[if IE 8] <html class="no-js lt-ie9">
/ [if gt IE 8]><!
%html.no-js
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title TaxBestimates
    %meta{:content => "Increase your take home pay with each paycheck.", :name => "description"}/
    %meta{:content => "Join TaxBestimates!", :property => "og:title"}/
    %meta{:content => "http://www.taxbestimates.com/img/fb-og-img.png", :property => "og:image"}/
    %meta{:content => "TaxBestimates", :property => "og:site_name"}/
    %meta{:content => "Increase your take home pay with each paycheck.", :property => "og:description"}/
    %meta{:content => "http://www.taxbestimates.com", :property => "og:url"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "index, follow", :name => "robots"}/
    = stylesheet_link_tag :funnel
    = favicon_link_tag 'favicon.ico', type: 'image/icon'
    = csrf_meta_tag
  %body.home.cs
    #fb-root
    :javascript
      (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=519024581485885&version=v2.0";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
    /[if lt IE 7]
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    .container
      .row.cshead
        .col-md-6.csheadl
          =image_tag "static_pages/tz-logo-home.png"
        .col-md-6.csheadr
          .fb-like{"data-action" => "like", "data-href" => "http://www.taxbestimates.com", "data-layout" => "button_count", "data-share" => "true", "data-show-faces" => "false"}
          .tw
            %a.twitter-share-button{"data-hashtags" => "taxbestimates", "data-url" => "http://www.taxbestimates.com", :href => "https://twitter.com/share"} Tweet
            :javascript
              !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
      .row.cscontm
        .col-md-8.col-md-offset-2
          %h1 The simplest way to understand your personal tax position
        .row.steps
          .col-md-12.mailerx
            %h3 Join the waiting list and be part of the beta team to optimize your paycheck and manage your year-end taxes.
            .form-group
              %input.form-control.input-lg.emailcs#join-list-email{:placeholder => "Enter your email for early access", :type => "text"}/
              .alert-container.alert{role: 'alert'}
              %a.btn.btn-primary.btn-lg.btn-block.caps.csbtn#join-list-btn{:href => "#", :role => "button"} Join the List
          .col-md-12
            %h2 How TaxBestimates Works
          .col-md-3
            =image_tag "funnel/step1.png"
            Provide us with some basic background information about yourself.
          .col-md-3
            =image_tag "funnel/step3.png"
            Tell us about your income and deduction details for the current year to date.
          .col-md-3
            =image_tag "funnel/step4.png"
            View your estimated tax liability or refund.
          .col-md-3
            =image_tag "funnel/step5.png"
            We provide recommendations so you can better manage your estimated tax refund or liability.
    = javascript_include_tag :funnel
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59197795-1', 'auto');
      ga('send', 'pageview');

app/views/static_pages/index.html.haml
.home
  = render partial: "layouts/static/static_header"
  .jumbotron
    .container
      %h1 Increase your take home pay with each paycheck
      %p
        %a.playvid{"data-remote" => "http://player.vimeo.com/video/80629469", "data-toggle" => "lightbox", :href => "http://vimeo.com/80629469"}
          =image_tag "static_pages/playvid.png"
      %p
        %a.btn.btn-primary.btn-lg{:href => "register", :role => "button"} Get Started
  .container
    .row.homecont
      .col-md-4
        =image_tag "static_pages/employee.png"
        %h2 Employees
        %p Manage your taxes as a regular employee
      .col-md-4
        =image_tag "static_pages/contractor.png"
        %h2 Contractors
        %p Manage your taxes as an independent contractor
      .col-md-4
        =image_tag "static_pages/bizowner.png"
        %h2 Business Owners
        %p Manage your taxes as the owner of an LLC, Sole Prop, or Partnership

app/views/static_pages/privacy_policy.html.haml
= content_for :title, "Privacy Policy"
%section#privacy.document
  .container
    %h2.section-title TaxBestimates Privacy Policy

    %p Your privacy is very important to us. This Privacy Policy is designed to help you understand how we handle your personal information, and we encourage you to read it carefully so that you can make informed decisions about what information you share with us.

    %p Unless defined in this Privacy Policy, the capitalized words and phrases below are defined in our Terms of Service, which we encourage you to read with this Privacy Policy. When you use the Service, you agree to this Privacy Policy and our Terms of Service.

    %h2.section-header WHAT INFORMATION DO WE COLLECT?

    %h4.ss-title We collect some of your personal information

    %p The Service collects and stores some of your personal information, which includes information that may be used to identify you. Your name, email address, physical address, telephone number, and social security number are personal information, as is information about your finances, such as your bank account details, tax returns, and any information we receive from your payroll provider. These are only a few examples of the personal information that you may share with us when you use the Service.

    %p You may share personal information with TaxBestimates in several ways, including by visiting our website, registering an account, using features of the Service, or contacting us for support. We may not be able to offer you access to the Service unless you provide us with your personal information.

    %h4.ss-title We use cookies to recognize your computer.

    %p TaxBestimates uses “cookies,” tiny text files that reside on your computer, to enable you to access the Service. Cookies help us recognize your computer when you visit our website and use the Service, but they do not contain any personal information about you. We, along with our affiliates and some other third parties, may use cookies to learn about how you use the Service and interact with advertisements.

    %p You can configure your browser to notify you when a website asks to store a cookie on your computer, or you can choose to block cookies entirely. However, some parts of the Service may rely on cookies in order to function properly. If you refuse to accept cookies, you may have difficulty using the Service.

    %h4.ss-title We do not store your payment information.

    %p If you pay for the Service using a credit card, TaxBestimates staff will not have access to your credit card details. Your payment information will be encrypted and securely stored by our credit card processor.

    %h2.section-header HOW DO WE USE YOUR INFORMATION?

    %h4.ss-title We limit the ways we use your personal information.

    %p TaxBestimates collects your personal information so that you can use the Service and its various features. We use the information we collect for a variety of related purposes. For example, we may use your personal information to verify your identity, keep in touch with you, give you access to features, keep you informed about changes to the Service, introduce you to new products from us and from third parties, help you resolve technical issues, and comply with laws and regulations.

    %p When you use the Service, you agree that we may collect your personal information, store it, and use it in these ways and in any others that you authorize or request.

    %h4.ss-title You may ask us to share information with third parties.

    %p
      %u Electronic Filing.
      You may ask us to electronically file your tax return, in which case we will be required to disclose identifying information about you to the Internal Revenue Service (“IRS”) as part of the electronic filing process. In addition to any information you have provided for the purpose of populating your tax return, we may need to share additional data including the Internet Protocol address of the computer from which you submitted the return and the email address associated with your account. When you use the electronic filing feature, you agree that we may disclose to the IRS any information they request, and you permit us to store and maintain all information necessary to comply with applicable laws.

    %p
      %u Third Party Login.
      The Service may enable you to grant another user, such as a tax advisor, permission to access your account and view your personal information using a Third Party Login. When you use this feature, you authorize us to share your personal information with that third party. It is important that you only grant a Third Party Login to people you know and trust, because we cannot control or take responsibility for the ways in which they use the personal information stored in your account.

    %p
      %u Third Party Products.
      You may ask us to share your personal information with a Third Party Product. By making such a request, you give us permission to transfer information from your account to a service controlled by a third party, and you agree that you and your information will be subject to that Third Party Product’s terms and conditions and privacy policy. Please be sure that you trust any third parties with whom you direct us to share your information, because we have no control over how they will use it.

    %h4.ss-title You may ask for access to your personal information.

    %p You are responsible for keeping the personal information stored by the Service accurate and up-to-date. You can request access to information associated with your account, or ask us to modify any information we have stored, by emailing your request to [info@TaxBestimates.com] . We will process your request as soon as we reasonably can, unless we are legally prevented from doing so. If we cannot honor your request, we will notify you.

    %p We will store your personal information only for as long as is necessary to give you access to the Service. Under some circumstances, including those noted above, we may be required by law to refrain from deleting your personal information until a certain amount of time has passed. When you share your personal information with us, you give us permission to store it for any length of time that may be legally required, or longer if we have a reasonable business need to do so.

    %h4.ss-title We aggregate some non-personally identifiable information.

    %p When you use the Service, you authorize us to collect, aggregate and use certain information associated with your account. The information we gather will never identify you or any other user of the Service, but we may use it to help us understand how you and other users interact with the Service, introduce users to new ways of using the Service, and improve the Service.

    %h4.ss-title We may disclose your personal information under other limited circumstances.

    %p On occasion, TaxBestimates may need to disclose your personal information to third parties in order to comply with court orders, subpoenas, or legal investigations, including those conducted by tax authorities. We will try to notify you if we are legally required to share your information with a third party without your consent, provided that it is possible and legal for us to do so.

    %h2.section-header HOW DO WE STORE YOUR INFORMATION?

    %h4.ss-title We are committed to protecting your personal information.

    %p We are committed to keeping your personal information secure. We take all reasonable precautions to prevent unauthorized access, modification, or disclosure. We store your personal information on secure serves and use SSL encryption to secure all data transferred between you and the Service.

    %p You can help us protect your personal information by keeping your account password safe. Change your password and let us know immediately if you think that someone has stolen or misused it. When you share information with us, you do so at your own risk and you should take care to only access and transmit information to the Service from a trusted device in a secure environment.

    %p Despite our efforts, we cannot guarantee that your information will be secure at all times. If we discover that a security breach has compromised your personal information in some way, such as by loss, theft, or unauthorized use, we will alert you at the first reasonable opportunity.

    %h2.section-header HOW DO WE COMMUNICATE WITH YOU?

    %h4.ss-title You may contact us with questions or concerns about privacy.

    %p If you have a question or concern about the way we have handled your personal information, please get in touch with us by email at [info@TaxBestimates.com] . Include as much detail as possible in your message and provide any additional documentation that may be relevant.

    %h4.ss-title You can decline to receive most email communications.

    %p TaxBestimates sends a variety of information to the email address you share with us when you register an account, including information about our products and your subscription to the Service. Every email that you receive from us will contain straightforward instructions for removing yourself from our mailing lists. We will promptly honor any removal requests you make, although we will continue to send emails containing critical information related to your use of the Service.

    %h4.ss-title We may update this policy.

    %p TaxBestimates reserves the right to modify this Privacy Policy at any time. Any amendments we make will be reflected on this website, and will become effective at the time they are posted. We will try to make you aware of any significant changes by reaching out through email or displaying a notification within the Service. By continuing to use the Service, you agree to be bound by any changes we make to this Policy.