config/routes.rb
Rails.application.routes.draw do

  get 'user/new'

  root 'website#home'

  namespace :api do
    resources :computations do
      collection do
        get :latest
      end
      member do
        get :form1040ez
        get :form540ez
      end
      resources :jobs do
        get :w4
        get :stateW4
      end
      resources :spouse do
        resources :jobs do
          get :w4
          get :stateW4
        end
      end
    end

    resources :draft_computations do
      collection do
        post :generate_actual_computation
      end
    end

    resources :invitations do
      collection do
        post :save_invite
      end
    end
  end

  namespace :admin do
    root 'dashboard#index'
    post 'refresh-graph', to: "dashboard#graph_info"

    get 'users' => 'user#index'
    get 'users/export' => 'user#export'
    put 'users/toggle' => 'user#toggle'

    put 'video/toggle' => 'video#toggle'
    put 'video/primary' => 'video#set_primary'

    resources :video do
    end
  end

  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :update => "update", :destroy => "destroy" }, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "forgot-password", to: "devise/passwords#new"
    get "change-password", to: "devise/passwords#edit"
    post "users/avatar", to: "registrations#avatar"
  end

  get 'home' => 'static_pages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'terms-and-conditions' => 'static_pages#terms_and_conditions'
  get 'tax' => 'tax#index'
  get 'resources' => 'video#index'

  get 'robots.txt' => 'static_pages#robots'

  #get 'funnel' => 'static_pages#funnel'
end

app/controllers/admin/dashboard_controller.rb
# app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
	include ActionView::Helpers::NumberHelper

	def index
		@total_users = User.count
		@active_users = User.where("deactivated_at IS NULL").count
		@inactive_users = @total_users - @active_users

		# user growth
		users_before = User.where("DATE(created_at) = ?", Date.today - 1).count
		users_now = User.where("DATE(created_at) = ?", Date.today).count

		@user_growth = user_growth(users_before, users_now)

		user_totals = get_user_totals('12-mos')
		@labels, @data = get_metric(user_totals, 'total-users', '12-mos')
	end

	def user_growth(before, now)
		if before == 0
			if now == 0
				0
			else
				100
			end
		elsif before > now
			0
		else
			((now - before) / before) * 100
		end
	end

	def graph_info
		user_totals = get_user_totals(params[:period])
		labels, data = get_metric(user_totals, params[:metric], params[:period])

		case params[:metric]
			when "total-users"
				title = "Total Users"
			when "user-growth"
				title = "User Growth"
			end

		respond_to do |format|
		  format.json do
		  	render json: {
		  		title: title,
		  		labels: labels,
		  		data: data,
		  		success: true
		  	}.to_json
		  end
		end
	end

	def get_user_totals(period)
		case period
		when "12-mos"
			User.group_by_month(:created_at, format: "%Y-%m-%d", last: 12).count
		when "7-days"
			User.group_by_day(:created_at, format: "%Y-%m-%d", last: 7).count
		end
	end

	def get_previous_total(period)
		case period
		when "12-mos"
			User.where('extract(month from created_at) = ? and extract(year from created_at) = ?', 13.months.ago.month, 13.months.ago.year).count
		when "7-days"
			User.where('extract(day from created_at) = ?', 8.days.ago.day).count
		end
	end

	def get_metric(user_totals, metric, period)
		labels = Array.new
		data = Array.new
		current_year = nil
		previous_total = get_previous_total(period)

		user_totals.each do |row|
			date = DateTime.parse(row[0])
			year = date.strftime("%Y")

			case period
			when "12-mos"
				if current_year != year
					labels.push(date.strftime("%b %Y"))
					current_year = year
				else
					labels.push(date.strftime("%b"))
				end
			when "7-days"
				labels.push(date.strftime("%b %e"))
			end

			case metric
			when "total-users"
				data.push(row[1])
			when "user-growth"
				data.push(user_growth(previous_total, row[1]))
			end

			previous_total = row[1]
		end

		return labels, data
	end
end

app/views/admin/dashboard/index.html.haml
.dashboard-content
	.container.dashboard-text-container
		.row
			.col-xs-12.dashboard-text.text
				TaxBestimates statistics as of 
				= Time.now.strftime("%B %d, %Y %l:%M %p")
	.container.dashboard-data
		.row
			%table.table.table-bordered
				%tbody
					%tr
						%td.col-xs-3.result-box
							.sub-text User Count
							.value.blue
								= @total_users
						%td.col-xs-3.result-box
							.sub-text Active Users
							.value.blue
								= @active_users
						%td.col-xs-3.result-box
							.sub-text User Growth (Day)
							.value{:class => "#{@user_growth > 0 ? 'green' : 'red'}"}
								= number_to_percentage(@user_growth, :precision => 2, :strip_insignificant_zeros => true)
						%td.col-xs-3.result-box
							.sub-text User Churn
							.value.red
								= @inactive_users
		.row
			.graph-box
				.graph-filters#filters
					.filter
						%label Select a metric
						%select.filter-input{:name => 'metric'}
							%option{:value => 'total-users', :selected => true} Total Users
							%option{:value => 'user-growth'} User Growth
					.filter
						%label Period
						%select.filter-input{:name => 'period'}
							%option{:value => '12-mos', :selected => true} Last 12 Months
							%option{:value => '7-days'} Last 7 Days
				.graph-container#graph-container
					%canvas#graph
:javascript
	var labels = #{@labels};
	var data = #{@data};
	var refresh_path = "#{admin_refresh_graph_path}";