config/routes.rb
Rails.application.routes.draw do

  get 'user/new'

  root 'website#home'

  namespace :api do
    resources :computations do
      collection do
        get :latest
      end
      member do
        get :form1040ez
        get :form540ez
      end
      resources :jobs do
        get :w4
        get :stateW4
      end
      resources :spouse do
        resources :jobs do
          get :w4
          get :stateW4
        end
      end
    end

    resources :draft_computations do
      collection do
        post :generate_actual_computation
      end
    end

    resources :invitations do
      collection do
        post :save_invite
      end
    end
  end

  namespace :admin do
    root 'dashboard#index'
    post 'refresh-graph', to: "dashboard#graph_info"

    get 'users' => 'user#index'
    get 'users/export' => 'user#export'
    put 'users/toggle' => 'user#toggle'

    put 'video/toggle' => 'video#toggle'
    put 'video/primary' => 'video#set_primary'

    resources :video do
    end
  end

  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :update => "update", :destroy => "destroy" }, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "forgot-password", to: "devise/passwords#new"
    get "change-password", to: "devise/passwords#edit"
    post "users/avatar", to: "registrations#avatar"
  end

  get 'home' => 'static_pages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'terms-and-conditions' => 'static_pages#terms_and_conditions'
  get 'tax' => 'tax#index'
  get 'resources' => 'video#index'

  get 'robots.txt' => 'static_pages#robots'

  #get 'funnel' => 'static_pages#funnel'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_presence_of :first_name, :last_name
  validates_confirmation_of :password
  has_many_documents :computations
  has_one_document :draft_computation
  has_attached_file :avatar, styles: { medium: "200x200#", thumb: "45x45#" }, default_url: "user/no-photo.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/, :size => { :less_than => 1.megabyte }

  self.per_page = 20

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def account_active?
    deactivated_at.nil?
  end

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    account_active? ? super : :locked
  end

  # instead of deleting, indicate the user requested a delete & timestamp it  
  def soft_delete
    update_attribute(:deactivated_at, Time.current)
  end

  def reactivate_account
    update_attribute(:deactivated_at, nil)
  end

  def self.to_csv(options = {})
    attributes = %w{full_name email account_active?}

    CSV.generate(options) do |csv|
      csv << attributes
      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  def self.search(search)
    if search
      where('first_name LIKE ? OR last_name LIKE ? or email LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/admin/user_controller.rb
# app/controllers/admin/user_controller.rb
class Admin::UserController < Admin::BaseController
  helper_method :sort_column, :sort_direction

	def index
=begin
    @filing_status = {
      'single' => "Single",
      'married_filing_joint' => "Married Filing Joint"
    }

    @users = BaseComputation.collection.aggregate(
      [
        {
          "$group" => {
            _id: "$user_id",
            id: { "$last" => "$_id" },
            first_name: { "$last" => "$first_name" },
            last_name: { "$last" => "$last_name" },
            mi: { "$last" => "$mi" },
            birth_month: { "$last" => "$birth_month" },
            birth_day: { "$last" => "$birth_day" },
            birth_year: { "$last" => "$birth_year" },
            filing_status: { "$last" => "$filing_status" },
            city: { "$last" => "$city" },
            state: { "$last" => "$state" },
            user_id: { "$last" => "$user_id" }
          }
        },
        {
          "$sort" => { sort_column => sort_direction == "asc" ? 1 : -1 }
        }
      ]
    )

    @parents = {}

    @users.each do |u|
      parent = User.where(:id => u['user_id'])

      if not parent.blank?
        @parents[u['id'].to_s] = parent.to_a[0]
      end
    end
=end
    @users = User.search(params[:search]).order("deactivated_at desc, " + sort_column + " " + sort_direction).paginate(:per_page => params[:per_page], :page => params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
	end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def toggle
    if params[:toggle] == 'deactivate'
      User.find(params[:id]).soft_delete
    else
      User.find(params[:id]).reactivate_account
    end

    flash[:type] = "success"
    flash[:notice] = "User has been " + params[:toggle] + "d."

    respond_to do |format|
      format.json do
        render json: {
          success: true
        }.to_json
      end
    end
  end
end

app/views/layouts/user/_static_footer.html.haml
%footer.footer
  .container
    .row
      .col-xs-8
        %span
          \© #{ Time.now.year } TaxBestimates Inc. All rights reserved.
          = succeed "|" do
            %a{:href => "terms-and-conditions"} Terms and Conditions
          %a{:href => "privacy-policy"} Privacy Policy
      .col-xs-4.text-right
        .fb-like{"data-action" => "recommend", "data-href" => "https://www.facebook.com/TaxBestimatesInc", "data-share" => "true", "data-layout" => "button_count", "data-show-faces" => "false"}
        %a.icon{href: "https://www.facebook.com/TaxBestimatesInc", target: "_blank", title: "Facebook"}
          %span.tz-facebook
        %a.icon{"data-hashtags" => "taxbestimates", "data-url" => "http://www.taxbestimates.com", :href => "https://twitter.com/share"}
          %span.tz-twitter

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-69529108-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/user/_static_header.html.haml
.banner
  .container
%nav.navbar.main-navbar.navbar-inverse{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        =image_tag "common/logo-user.png"
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li{:class => request.env['PATH_INFO'] == resources_path ? "active" : ''}
            %a{:href => resources_path} Resource Center
          %li.dropdown
            %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false", :id => "user-menu"}
              - if @user.avatar.exists?
                =image_tag @user.avatar.url(:thumb), class: 'user-photo'
              - else
                =image_tag "user/no-photo.png", class: 'user-photo'
              %span.name#header-full-name #{current_user.full_name}
              =image_tag "user/arrow-down.png"
            %ul.dropdown-menu.top{"aria-labelledby" => "user-menu"}
              %li
                %a{:href => "#", "data-toggle" => "modal", "data-target" => "#edit-account-form"} Edit Account
              %li
                %a{:href => "mailto:info@taxbestimates.com"} Contact Us
              %li
                %a{:href => "logout"} Logout
        - else
          %li
            = link_to "Home", root_path
          %li
            = link_to "About", about_path
          %li
            = link_to "Contact Us", contact_path
          %li
            %a.signin{"data-target" => "#loginmodal", "data-toggle" => "modal"} Sign In
= render partial: "devise/registrations/edit"

app/views/layouts/user/_sub_nav.html.haml
.sub-nav-container
  .sub-nav
    %nav.navbar.sub-navbar{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#sub-navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #sub-navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li#sub-dashboard
              %a{:href => "/tax#dashboard"}
                %span.icon.icon-dashboard>
                Dashboard
            %li#sub-personal-information
              %a{:href => "/tax#personal_information/1"}
                %span.icon.icon-info>
                Personal Information
            %li#sub-recommendations
              %a{:href => "/tax#options"}
                %span.icon.icon-recommendations>
                Tax Options
            %li#sub-archive
              %a{:href => "/tax#archive"}
                %span.icon.icon-archive>
                Computation Archive
            %li#sub-annual-filing
              %a{:href => "/tax#annual_filing"}
                %span.icon.icon-filing>
                Annual Filing
          - if current_user.admin == true
            %ul.nav.navbar-nav.navbar-right
              %li#sub-admin.pull-right
                %a{:href => "/admin"}
                  %span.icon.icon-admin>
                  Switch to Admin

app/views/layouts/user/application.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8">
/[if IE 8] <html class="no-js lt-ie9">
/ [if gt IE 8]><!
%html.no-js
  / <![endif]
  %head
    = stylesheet_link_tag :user
    = javascript_include_tag :application
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %title
      = 'TaxBestimates'
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "noindex, nofollow", :name => "robots"}/
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tag
  %body
    #fb-root
    :javascript
      var user_path = "#{ :user }/";

      (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=519024581485885&version=v2.0";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
    /[if lt IE 7]
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    - unless current_page?(root_url)
      = render partial: "layouts/user/static_header"
    = yield
    / /container
    = render partial: "layouts/user/static_footer"