config/routes.rb
Rails.application.routes.draw do

  get 'user/new'

  root 'website#home'

  namespace :api do
    resources :computations do
      collection do
        get :latest
      end
      member do
        get :form1040ez
        get :form540ez
      end
      resources :jobs do
        get :w4
        get :stateW4
      end
      resources :spouse do
        resources :jobs do
          get :w4
          get :stateW4
        end
      end
    end

    resources :draft_computations do
      collection do
        post :generate_actual_computation
      end
    end

    resources :invitations do
      collection do
        post :save_invite
      end
    end
  end

  namespace :admin do
    root 'dashboard#index'
    post 'refresh-graph', to: "dashboard#graph_info"

    get 'users' => 'user#index'
    get 'users/export' => 'user#export'
    put 'users/toggle' => 'user#toggle'

    put 'video/toggle' => 'video#toggle'
    put 'video/primary' => 'video#set_primary'

    resources :video do
    end
  end

  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register", :update => "update", :destroy => "destroy" }, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "forgot-password", to: "devise/passwords#new"
    get "change-password", to: "devise/passwords#edit"
    post "users/avatar", to: "registrations#avatar"
  end

  get 'home' => 'static_pages#index'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'privacy-policy' => 'static_pages#privacy_policy'
  get 'terms-and-conditions' => 'static_pages#terms_and_conditions'
  get 'tax' => 'tax#index'
  get 'resources' => 'video#index'

  get 'robots.txt' => 'static_pages#robots'

  #get 'funnel' => 'static_pages#funnel'
end

app/models/video.rb
class Video < ActiveRecord::Base
	validates :title, :url, :presence => true

	def deactivate
    update_attribute(:active, false)
  end

  def reactivate
    update_attribute(:active, true)
  end

  def set_primary
  	Video.update_all(:primary => false)
  	update_attribute(:primary, true)
  end

	def self.search(search)
    if search
      where('title LIKE ? OR description LIKE ? or url LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Video.all
    end
  end
end

app/controllers/admin/video_controller.rb
# app/controllers/admin/video_controller.rb
class Admin::VideoController < Admin::BaseController
  helper_method :sort_column, :sort_direction

	def index
    @videos = Video.search(params[:search]).order("\"primary\" desc, active desc, " + sort_column + " " + sort_direction).paginate(:per_page => params[:per_page], :page => params[:page])
	end

  def sort_column
    Video.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def toggle
    if params[:toggle] == 'deactivate'
      Video.find(params[:id]).deactivate
    else
      Video.find(params[:id]).reactivate
    end

    flash[:type] = "success"
    flash[:notice] = "Video has been " + params[:toggle] + "d."

    respond_to do |format|
      format.json do
        render json: {
          success: true
        }.to_json
      end
    end
  end

  def set_primary
    Video.find(params[:id]).set_primary

    flash[:type] = "success"
    flash[:notice] = "Primary video has been set."

    respond_to do |format|
      format.json do
        render json: {
          success: true
        }.to_json
      end
    end
  end

  def create
    data = {
      :title => params[:title],
      :url => params[:url],
      :description => params[:description],
      :active => true
    }

    Video.create(data)

    flash[:type] = "success"
    flash[:notice] = "Video has been added."

    redirect_to admin_video_index_path
  end

  def update

  end

  def destroy
    Video.destroy(params[:id])

    flash[:type] = "success"
    flash[:notice] = "Video has been deleted."

    respond_to do |format|
      format.json do
        render json: {
          success: true
        }.to_json
      end
    end
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  before_filter :login_required

  def index
  	@user = current_user

    @latest = @user.computations.last
    @draft = @user.draft_computation

    @latest = @latest.present? ? ComputationPresenter.new(@latest) : {}
    @draft = @draft.present? ? ComputationPresenter.new(@draft) : {}
    
    render layout: 'layouts/user/application'
  end
end

app/views/admin/video/_table.html.haml
.row
	.col-xs-12
		%table.table.table-striped.table-hover.table-panel.sortable
			%thead
				%tr
					%th
					%th
						= sortable "title"
					%th
						= sortable "url", "URL"
					%th
			%tbody
				- if @videos.length > 0
					- @videos.each do |u|
						%tr
							%td
								- if u.primary == true
									%span.glyphicon.glyphicon-star.text-info{:title => "Primary"}
							%td #{u.title}
							%td
								%a{:href => u.url, :target => "_blank"}
									= u.url
							%td.options
								%a.edit-row{:href => '#', 'data-type' => 'video', 'data-id' => u.id} Edit
								- if u.primary == false
									%a.set-primary{:href => '#', 'data-form-method' => 'PUT', 'data-form-action' => 'primary', 'data-type' => 'video', 'data-id' => u.id} Set as Primary
								- if u.active == true
									- if u.primary == false
										%a.toggle-row.deactivate{:href => '#', 'data-form-method' => 'PUT', 'data-form-action' => 'deactivate', 'data-type' => 'video', 'data-id' => u.id} Deactivate
								- else
									%a.toggle-row.activate{:href => '#', 'data-form-method' => 'PUT', 'data-form-action' => 're-activate', 'data-type' => 'video', 'data-id' => u.id} Re-activate
								- if u.primary == false
									%a.delete-row{:href => '#', 'data-form-method' => 'DELETE', 'data-type' => 'video', 'data-id' => u.id} Delete
				- else
					%tr.placeholder
						%td.text-center{:colspan => 4}
							No videos yet.
	.row.table-options
	.col-xs-3
		%ul.list-inline
			%li Items per page
			%li
				= per_page_link 20
			%li
				= per_page_link 50
			%li
				= per_page_link 100
			%li
				= per_page_link 250
	.col-xs-8.col-xs-offset-1.text-right
		Page #{ @videos.current_page }
		%em of
		= @videos.total_pages
		= will_paginate @videos, { :previous_label => "", :next_label => "" }

app/views/admin/video/index.html.haml
.dashboard-content
	.container.dashboard-text-container
		%form.form-inline{:method => 'get', :action => admin_video_index_path }
			.row
				.col-xs-6.form-group
					%label{:for => 'search-query'} Search by
					= text_field_tag :search, params[:search], {:class => "form-control", :id => "search-query", :placeholder => "Title, description, or URL"}
				.col-xs-6.text-right
					%button#add-item.btn.btn-primary{:type => "button"}
						Add Video
	.container#users-table.dashboard-data
		- if flash[:notice]
			.alert{:class => "alert-" + flash[:type]}
				= flash[:notice]
		= render 'table'
#message-box.modal{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
	.modal-dialog.modal-prompt
		.modal-content
			.modal-body
				%button.close{"aria-label" => "close", "data-dismiss" => "modal", :type => "button"}
					%img{:alt => "&amp;times;", :aria => "{:hidden=&gt;&quot;true&quot;}", :src => asset_path("common/modal-close.png")}
				%span.message
			.modal-footer
				%button#btn-confirm.btn.btn-primary{"data-dismiss" => "modal", :type => "button"} Yes
				%button#btn-deny.btn.btn-default{"data-dismiss" => "modal", :type => "button"} No
#data-form.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		%form{:method => "post", :action => admin_video_index_path}
			.modal-content
				.modal-header
					%button.close{"aria-label" => "close", "data-dismiss" => "modal", :type => "button"}
						=image_tag "common/modal-close.png", alt: "&times;", aria: { hidden: "true" }
					.modal-title
				.modal-body
					.form-group
						%label{:for => 'video-title'} Video Title
						%input#video-title.form-control{:name => "title", :type => "text", :placeholder => "Title", :required => true}
					.form-group
						%label{:for => 'video-url'} Embed URL
						%input#video-title.form-control{:name => "url", :type => "url", :placeholder => "URL", :required => true}
					.form-group
						%label{:for => 'video-description'} Description
						%textarea#video-description.form-control{:name => "description", :rows => 4, :placeholder => "Short description"}
				.modal-footer
					%input#item-id{:type => "hidden"}
					= hidden_field_tag :authenticity_token, form_authenticity_token
					.pull-right
						%button.btn.btn-default{:type => "button", "data-dismiss" => "modal"} Close
						%button.btn.btn-primary{:type => "submit"} Save

:javascript
	var data_path = "#{ admin_video_index_path }";
	var set_primary_path = "#{ admin_video_primary_path }";
	var toggle_path = "#{ admin_video_toggle_path }";